[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
poem = "1.3.35"
serde = "1.0"
shuttle-service = { version = "0.5.0", features = ["sqlx-postgres", "secrets", "web-poem"] }
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres"] }
